#!/usr/bin/env bash

set -eu

CUR_DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)

source ${CUR_DIR}/erc20-util
source ${CUR_DIR}/relayer-util

function debugMode() {
  if [ -n "${1+x}" ] && [ "$1" = "--debug" ]; then
    set -x
  fi
}
